### ISSUE TITLE
KV Namespace and Binding to store last nickname updated timestamp

### ISSUE THREAD

**Issue by bharati-21** [Real-Dev-Squad/cron-jobs#12]
Create the following KV Namespace and binding in Cloudflare to store the last discord nickname updated timestamp.

# ❗️Important
- This ticket when done closes 
- https://github.com/Real-Dev-Squad/website-backend/issues/1119 and
- https://github.com/Real-Dev-Squad/cron-jobs/pull/11

> Please execute the below mentioned commands ***only*** within the `cron-jobs` repository code.

## Step 1: Enable Permissions
- Navigate to cloudflare dashboard, click on the account icon in the top right and select ***My Profile*** from the dropdown.
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/ae9a8a8f-e64d-40f6-af4c-9a1e0d48be21)
- In the profile dashboard, from the left sidebar, select ***API Tokens***.
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/b1b7e58b-eca1-4fd6-9221-73223aafa2a6)
- Ensure the following 2 permissions (among others) are present: 
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/4be75cc8-5488-4949-9c68-f92cc84e7d2f)
- If not, create a new token based on the ***Edit Cloudflare Workers*** template keeping the default permissions and other values.
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/26b9ea28-94cc-4f25-a02e-db7d6780320a)

## Step 2: Create Namespace
- Create Namespace `CronJobsTimestamp` which will contain the binding used to refer the KV namespace
- This step can be performed either via the command line or the Cloudflare dashboard.

### Create via `wrangler` command
- Type the command given below. Make sure to replace `<environment>` with the environment the namespace is being created for. E.g. `staging` or `production`.
```
npx wrangler kv:namespace create TEST_NAMESPACE --env=<environment>
```
- The above command will generate the following which should be added to the `wrangler.toml` file in the `cron-jobs` repository under the specified environment, e.g. `[env.production]`
```
{ binding = "<binding_name>", id = "<binding_id>" }
```
- After this step, we should be able to see the binding with `cron-jobs-CronJobsTimestamp` in the Cloudflare dashboard.
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/3171dbd0-bd19-4f99-b4f1-615eba808c19)

### Create via Cloudflare dashboard
- Navigate to `https://dash.cloudflare.com/`. 
- From the left pane/ sidebar, select `Workers & Pages`, and then choose `KV`.
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/1a153015-f29c-4881-bf06-fe249a424db0)
- Click on the `Create a namespace` button and then type the name of the namespace `CronJobsTimestamp` and then click `Add`.
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/0791490c-06d4-4730-8bbb-e8af7c13cd17)
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/77300895-7589-48a1-8c7d-c6d27970a795)

- Once added, from the list of namespaces, check for the newly created one and click `View`.
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/13392cb6-b7a7-4662-b3ba-a858722652b1)
- Select and copy both the Namespace name and id, and follow the same format mentioned above to add the new binding to the `wrangler.toml` file in the `cron-jobs` repository under the specified environment, e.g. `[env.production]`.
  ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/232fc6f0-c618-4cc5-8ced-adc416846191)

## Step 3: Create Key-Value (KV) pair
- Create KV that contains the timestamp of the last executed batch process that updated the discord nicknames
- This step can be performed either via the command line or the Cloudflare dashboard.

### Create via `wrangler` command
- Run the following command. Make sure to replace `<environment>` with the environment the namespace is being created for. E.g. `staging` or `production`.
```
npx wrangler kv:key put --binding=CronJobsTimestamp "DISCORD_NICKNAME_CHANGED" 0 --env=<environment>
```
- You should get the following result (of course, with the id of the namespace you created above).

### Create via Cloudflare dashboard
- Navigate to the namespace view dashboard by following the steps mentioned in Step 1 Create Namespace
- Type the KV name `DISCORD_NICKNAME_CHANGED` and the value `0`, and click on `Add entry`
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/ec384120-abb4-4d31-9c4d-d0b3e5b41347)
- You should be able to view the `DISCORD_NICKNAME_CHANGED` KV and its value in the list as shown in the image below 
   ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/19e28ef7-90ae-4323-a869-be8fae92a11d)

**Comment by ankushdharkar** [comment]
✅ Created this for production:
![Cron Jobs@2x](https://github.com/Real-Dev-Squad/cron-jobs/assets/1935403/a2d78471-3323-44bf-bc33-769ef3be354b)

**Comment by prakashchoudhary07** [comment]
Update the KV name, as its being changed as per suggestion in Pr review https://github.com/Real-Dev-Squad/cron-jobs/pull/11/files#r1375527051

<img width="1335" alt="image" src="https://github.com/Real-Dev-Squad/cron-jobs/assets/34452139/96b64327-38c6-46b2-818a-3c56db2aef9b">
