### ISSUE TITLE
Setting up tests

### ISSUE THREAD

**Issue by fakhruddinkw** [Real-Dev-Squad/cron-jobs#13]
Currently in CI, we are only checking for lint errors, and tests are disabled. We need to enable tests also.

**Comment by bharati-21** [comment]
Currently the tests are failing as the JWT package `tsndr/cloudflare-worker-jwt` needs to be mocked as done in the discord slash commands repository. 

Please refer this thread https://discord.com/channels/673083527624916993/673083527624917003/1176037933338333205
