### ISSUE TITLE
Share Auto Generated Namespace ID for Namespace Created in Cloudflare

### ISSUE THREAD

**Issue by bharati-21** [Real-Dev-Squad/cron-jobs#17]
- The auto generated namespace ID for the namespace created in Cloudflare needs be added to the `wrangler.toml` file so that the job can access the namespace.
- To retrieve the namespace ID from Cloudflare dashboard:
  1. Navigate to KV under the Workers & Pages option from the left sidebar
  2. From the list of namespaces, find `CronJobsTimestamp` binding and click on the copy icon. The copy icon will appear hovered over the namespace ID.
     ![image](https://github.com/Real-Dev-Squad/cron-jobs/assets/51514137/3026c976-2a11-4f41-9fa3-1d8ae3eef354)
  3. Share the copied namespace ID.

**Comment by prakashchoudhary07** [comment]
CornJobsTimestamp Id: 3a10f726c95d4afea9dee5fd00f029b9

**Comment by bharati-21** [comment]
Closing the issue as the namespace ID has been added to the wrangler.toml file
