### ISSUE TITLE
Add required environment variables for cron jobs STAGING

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/cron-jobs#27]
Add required environment variables for cron jobs STAGING

### Issue Description

- Following keys need to be added
    - [ ] DISCORD_BOT_API_URL (saved as `services.discordBot.baseUrl` in RDS backend env file)  
    - [ ] DISCORD_BOT_PRIVATE_KEY (saved as `rdsServerlessBot.rdsServerLessPrivateKey` in RDS backend env file)
    
### Steps to follow 

Add as secrets via Cloudflare Dashboard: 
- Log in to [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account.
- Select Workers & Pages.
- In Overview, select your Worker > Settings.
- Under Environment Variables, select Add variable.
- Input a Variable name and its value, which will be made available to your Worker.
- Select Encrypt to protect the secret’s value. This will prevent the value from being visible via Wrangler and the dashboard.
- (Optional) To add multiple secrets, select Add variable.
- Select Save to implement your changes.

**Comment by prakashchoudhary07** [comment]
Done

Keys in cron-jobs
 
<img width="834" alt="image" src="https://github.com/Real-Dev-Squad/cron-jobs/assets/34452139/9b2e17fc-580c-4444-b053-5a2705d7661b">
