### ISSUE TITLE
Add required environment variables for cron jobs PRODUCTION

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/cron-jobs#28]
### Issue Description
These variables are needed so that cron jobs can make a call to discord bot([discord slash command](https://github.com/Real-Dev-Squad/discord-slash-commands)). This call will bulk update roles for users. To make this call we need the following variables in our GitHub settings environment. 

- Following keys need to be added
    - [x] DISCORD_BOT_API_URL (saved as `services.discordBot.baseUrl` in RDS backend env file)  
    - [x] DISCORD_BOT_PRIVATE_KEY (saved as `rdsServerlessBot.rdsServerLessPrivateKey` in RDS backend env file)
    
### Steps to follow 

Add as env variables via GitHub actions environment variables for `cron-jobs` repository

#### Reference:
https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables

https://github.com/Real-Dev-Squad/website-backend/blob/develop/config/default.js
<img width="898" alt="Screenshot 2023-12-18 at 5 30 51 AM" src="https://github.com/Real-Dev-Squad/cron-jobs/assets/98796547/b9c9bd79-f32b-4a56-a6df-b4fd0d6bbc4a">
<img width="990" alt="Screenshot 2023-12-18 at 5 30 35 AM" src="https://github.com/Real-Dev-Squad/cron-jobs/assets/98796547/ac599897-c1d8-4dbc-9297-96511e72e504">

**Comment by ankushdharkar** [comment]
Added the url and key. Thank you for the detailed instructions.

**Comment by Ajeyakrishna-k** [comment]
@ankushdharkar, could you please verify whether the `DISCORD_BOT_PRIVATE_KEY` in the production environment of the `cron-jobs` GitHub repository and the `RDS_SERVERLESS_PRIVATE_KEY` in the backend configuration are the same?

- Please ensure to check for any leading or trailing spaces when comparing the `DISCORD_BOT_PRIVATE_KEY`.

Currently, the JWT token generated in `cron-jobs` is not being verified in the [discord slash command](https://github.com/Real-Dev-Squad/discord-slash-commands). We get the following error when we try to verify the token in discord-slash-command: "Invalid SPKI".
