### ISSUE TITLE
Add required environment variables for STAGING

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/cron-jobs#52]
Add required environment variables for PRODUCTION

## Please make these changes after merging these PR: 
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/181
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/182
- https://github.com/Real-Dev-Squad/cron-jobs/pull/55
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/191
- Create a new dev to main sync and merge

## Following keys need to be added:
- ### In Cron jobs Github Settings environment:  
    - [ ] DISCORD_BOT_PRIVATE_KEY (add the previous private key used in rds backend for backward compatilbility
    - [ ] `DISCORD_SERVICE_PRIVATE_KEY` (newly generated private key)
    - [ ] `FF_SELF_PRIVATE_KEY ` with value: 'true'
    
    
    
- ### In [Discord slash commands](https://github.com/Real-Dev-Squad/discord-slash-commands/) Github Settings environment:  
    - [ ] `CRON_JOBS_PUBLIC_KEY` (newly generated public key)

## Steps to generate private public keys:
Generate private key using : ```ssh-keygen -t rsa -P "" -b 2048 -m PEM -f jwtRS256.key```
View public key using : ```ssh-keygen -f jwtRS256.key.pub -e -m pkcs8```

**Comment by prakashchoudhary07** [comment]
Updated the configs, thanks for the details

**Comment by Ajeyakrishna-k** [comment]
- ### In Cron jobs Github Settings environment:  
    - [x] DISCORD_BOT_PRIVATE_KEY (add the previous private key used in rds backend for backward compatilbility
    - [x] `DISCORD_SERVICE_PRIVATE_KEY` (newly generated private key)
    - [x] `FF_SELF_PRIVATE_KEY ` with value: 'true'

**Comment by prakashchoudhary07** [comment]
@Ajeyakrishna-k For now we will make changes, 
We should always create new tickets for making changes, next time please don't reopen closed tickets,

**Comment by prakashchoudhary07** [comment]
Thanks for the details, this has been done 💀
