### ISSUE TITLE
Add required environment variables for PRODUCTION

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/cron-jobs#53]
### This issue has been moved to :
- https://github.com/Real-Dev-Squad/cron-jobs/issues/56

Add required environment variables for PRODUCTION

## Please make these changes after merging these PR: 
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/181
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/182
- https://github.com/Real-Dev-Squad/cron-jobs/pull/55
- https://github.com/Real-Dev-Squad/discord-slash-commands/pull/191
- Create a new dev to main sync and merge

## Following keys need to be added:
- ### In Cron jobs Github Settings environment:  
    - [ ] `DISCORD_SERVICE_PRIVATE_KEY` (newly generated private key)
    - [ ] `FF_SELF_PRIVATE_KEY` with value: 'true'
    
    
    
- ### In [Discord slash commands](https://github.com/Real-Dev-Squad/discord-slash-commands/) Github Settings environment:  
    - [ ] `CRON_JOBS_PUBLIC_KEY` (newly generated public key)

## Steps to generate private public keys:
Generate private key using : ```ssh-keygen -t rsa -P "" -b 2048 -m PEM -f jwtRS256.key```
View public key using : ```ssh-keygen -f jwtRS256.key.pub -e -m pkcs8```

**Comment by prakashchoudhary07** [comment]
Details may have changed, please refer #52 

Will be closing this issue, as requirements may have changed, will raise a new ticket with the updated details
