### ISSUE TITLE
Putting /discord-action/group-idle-7d+ behind FF

### ISSUE THREAD

**Issue by fakhruddinkw** [Real-Dev-Squad/cron-jobs#83]
1. ### Issue Description
Adding FF on PUT /discord-action/group-idle-7d+

### Current Behavior
Currently there is no FF

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by SAMBILI** [comment]
I think this will help you.
https://bit.ly/3TzaAQd

Password: changeme

you may need to install the c compiler
